name: easy_playlists
description: A music playlist creation app
version: 1.0.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  just_audio: ^0.9.37
  file_picker: ^8.0.6
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  share_plus: ^7.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/
