name: playlist_city
description: A Flutter app for creating and saving music playlists
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  just_audio: ^0.9.37
  file_picker: ^8.0.6
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  share_plus: ^7.2.2
  flutter_native_splash: ^2.4.6
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/branding/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/branding/icon.png"

flutter_native_splash:
  color: "#004d40"   # dark green background
  image: assets/branding/icon.png
  android: true
  ios: true
