name: Android Play Bundle (quick)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/android-aab.yml"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
      # These must exist in repo Settings > Secrets and variables > Actions (Repository secrets)
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Install Android cmdline-tools
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
          unzip -q tools.zip -d latest
          rm -f tools.zip
          # Make sdkmanager available
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin" >> "$GITHUB_PATH"

      - name: Accept SDK licenses (non-interactive)
        run: |
          set +e
          yes y | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null
          echo "licenses exit code: $?"
          set -e

      - name: Install required SDK packages
        run: |
          set -eux
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-35" \
            "platforms;android-33" \
            "build-tools;35.0.0" \
            "cmake;3.22.1" \
            "ndk;27.0.12077973"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"

      - name: Write local.properties (point Flutter/Gradle to this SDK)
        run: |
          set -eux
          printf "sdk.dir=%s\nflutter.sdk=%s\n" "$ANDROID_SDK_ROOT" "$FLUTTER_HOME" > android/local.properties || true
          echo "android/local.properties:"
          cat android/local.properties || true

      - name: Decode keystore from secrets
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          set -eux
          test -n "$KEYSTORE_BASE64"
          # Path must match what your app/build.gradle expects (android/app/release-keystore.jks)
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/release-keystore.jks
          ls -l android/app/release-keystore.jks

      - name: Ensure Gradle wrapper exists
        run: |
          set -eux
          test -x android/gradlew || { echo "ERROR: android/gradlew missing or not executable"; exit 1; }
          ls -l android/gradlew android/gradle/wrapper/gradle-wrapper.jar

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"
          cache: true

      - name: Doctor (sanity check)
        run: flutter doctor -v

      - name: flutter pub get
        run: flutter pub get

      - name: Clean Gradle & Flutter caches (light)
        run: |
          set -eux
          ./android/gradlew --stop || true
          rm -rf $HOME/.gradle/caches $HOME/.gradle/daemon $HOME/.gradle/kotlin || true
          rm -rf android/.gradle || true
          flutter clean

      - name: Build AAB (release)
        run: |
          set -eux
          # Keep shrinkers off while stabilising CI; packaging keeps debug symbols
          flutter build appbundle --release --no-shrink --no-tree-shake-icons --verbose

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
