name: Android Play Bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-aab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Restore keystore from secret
        run: echo "$KEYSTORE_BASE64" | base64 -d > $HOME/easyplaylists.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Write android/key.properties
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=${{ env.HOME }}/easyplaylists.jks
          EOF
      - name: Build AAB (release, light flags)
        run: flutter build appbundle --release --no-shrink --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
