      - name: Install SDK packages (per-package + retry)
        run: |
          set -e
          PKGS=(
            "platform-tools"
            "platforms;android-34"
            "build-tools;34.0.0"
            "cmake;3.22.1"
            "ndk;27.0.12077973"
          )
          echo "y" | sdkmanager --licenses || true

          install_pkg () {
            local p="$1"
            for i in 1 2 3; do
              echo "Attempt $i: installing $p"
              if sdkmanager --install "$p"; then
                echo "OK: $p"
                return 0
              fi
              echo "Retrying $p in 10s…"
              sleep 10
            done
            echo "FAILED: $p"
            exit 1
          }

          for p in "${PKGS[@]}"; do
            install_pkg "$p"
          done
