      - name: Retry: Set up Android SDK + install packages
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 10
          command: |
            echo "Installing Android SDK packages…"
            echo "y" | sdkmanager --licenses || true
            sdkmanager --install \
              "platform-tools" \
              "platforms;android-34" \
              "build-tools;34.0.0" \
              "cmake;3.22.1" \
              "ndk;27.0.12077973"

      - name: Verify SDK components
        run: |
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}"
          ls -la /usr/local/lib/android/sdk || true
          /usr/local/lib/android/sdk/cmdline-tools/*/bin/sdkmanager --list | head -n 200 || true
