name: Android Play Bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/android-aab.yml"

jobs:
  build-aab:
    name: Build Release AAB
    runs-on: ubuntu-latest
    timeout-minutes: 65

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Install Android SDK (manual)
        shell: bash
        run: |
          set -euxo pipefail

          export ANDROID_SDK_ROOT="$HOME/android-sdk"
          export ANDROID_HOME="$ANDROID_SDK_ROOT"
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"

          # Download recent cmdline-tools
          curl -L -o tools.zip "https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip"
          unzip -q tools.zip -d latest
          rm -f tools.zip

          # Resolve sdkmanager path (Google's zip sometimes nests 'cmdline-tools/')
          if [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          elif [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin/sdkmanager" ]; then
            SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin/sdkmanager"
          else
            echo "sdkmanager not found after unzip" >&2
            find "$ANDROID_SDK_ROOT/cmdline-tools" -maxdepth 3 -type f -name sdkmanager || true
            exit 127
          fi

          export PATH="$(dirname "$SDKMGR"):$ANDROID_SDK_ROOT/platform-tools:$PATH"

          yes | "$SDKMGR" --licenses

          # Install each package in its own call (avoids multi-line parse bug)
          "$SDKMGR" "platform-tools"
          "$SDKMGR" "platforms;android-34"
          "$SDKMGR" "build-tools;34.0.0"
          "$SDKMGR" "cmake;3.22.1"
          "$SDKMGR" "ndk;27.0.12077973"

      - name: Restore keystore from secret
        shell: bash
        run: |
          set -euxo pipefail
          test -n "$KEYSTORE_BASE64"
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/release-keystore.jks
          ls -lh android/app/release-keystore.jks

      - name: Build signed AAB
        shell: bash
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          set -euxo pipefail
          ./gradlew --no-daemon --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8" \
            bundleRelease

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
