name: Android Play Bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/android-aab.yml"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Install cmdline-tools and expose sdkmanager on PATH
      - name: Install Android commandline-tools
        run: |
          set -eux
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          cd "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
          unzip -q tools.zip -d latest
          rm -f tools.zip
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/bin" >> "$GITHUB_PATH"

      - name: Accept SDK licenses (non-interactive)
        run: |
          set +e
          yes y | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses >/dev/null
          echo "sdkmanager --licenses exit code: $?"
          set -e

      - name: Install required SDK packages
        run: |
          set -eux
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-35" \
            "platforms;android-33" \
            "build-tools;35.0.0" \
            "cmake;3.22.1" \
            "ndk;27.0.12077973"
          echo "$ANDROID_SDK_ROOT/platform-tools" >> "$GITHUB_PATH"

      - name: Decode keystore from secrets
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          set -eux
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/release-keystore.jks
          ls -l android/app/release-keystore.jks

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"
          cache: true

      - name: Doctor (sanity check)
        run: flutter doctor -v

      - name: flutter pub get
        run: flutter pub get

      - name: Clean Gradle/Flutter caches
        run: |
          set -eux
          ./android/gradlew --stop || true
          rm -rf $HOME/.gradle/caches $HOME/.gradle/daemon $HOME/.gradle/kotlin || true
          rm -rf android/.gradle || true
          flutter clean

      # Clean caches to avoid "Already watching path" and stale transforms
      - name: Clean Gradle/Flutter caches
        run: |
          set -eux
          ./android/gradlew --stop || true
          rm -rf $HOME/.gradle/caches $HOME/.gradle/daemon $HOME/.gradle/kotlin || true
          rm -rf android/.gradle || true
          flutter clean

      - name: Build AAB (release)
        env:
          # Give Gradle & Java more headroom and turn off VFS watch
          _JAVA_OPTIONS: "-Xmx2g -XX:MaxMetaspaceSize=512m"
          JAVA_TOOL_OPTIONS: "-Xmx2g -XX:MaxMetaspaceSize=512m"
          GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=512m" -Dorg.gradle.vfs.watch=false'
        run: |
          set -eux
          # Double-check the keystore exists where build.gradle expects it
          ls -l android/app/release-keystore.jks

          # Sanity: show gradle.properties that we just set (helps debugging)
          echo "----- android/gradle.properties ----"
          cat android/gradle.properties || true
          echo "------------------------------------"

          # Build via Flutter with shrinkers off to reduce R8 pressure
          flutter pub get
          flutter build appbundle --release --no-shrink --no-tree-shake-icons --verbose

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
