name: Android Play Bundle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/android-aab.yml"

jobs:
  build-aab:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # Give Java/Gradle more headroom on the runner
      JAVA_TOOL_OPTIONS: "-Xmx3g -XX:MaxMetaspaceSize=768m"
      _JAVA_OPTIONS: "-Xmx3g -XX:MaxMetaspaceSize=768m"
      # Flutter can be chatty with RAM during gen/build
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx3g -XX:MaxMetaspaceSize=768m' -Dkotlin.daemon.jvm.options='-Xmx1g -XX:MaxMetaspaceSize=512m'"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK (tools only)
        uses: android-actions/setup-android@v3

      - name: Install SDK/NDK packages (with retries)
        shell: bash
        run: |
          set -e
          echo "Accept licenses"
          yes | sdkmanager --licenses || true

          echo "Update sdkmanager"
          sdkmanager --update || true

          install_pkgs() {
            sdkmanager \
              "platform-tools" \
              "platforms;android-34" \
              "build-tools;34.0.0" \
              "cmake;3.22.1" \
              "ndk;27.0.12077973"
          }

          # retry up to 4 times in case of transient 5xx errors
          n=0
          until [ $n -ge 4 ]; do
            install_pkgs && break
            n=$((n+1))
            echo "sdkmanager failed; retry $n/4 after short sleep…"
            sleep 10
          done

          echo "Installed packages:"
          sdkmanager --list | sed -n '1,120p'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show tool versions
        run: |
          flutter --version
          java -version
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

      # Make Gradle conservative (single worker, no daemon) and disable shrinkers
      - name: Write CI gradle.properties
        run: |
          cat > android/gradle.properties <<'PROPS'
          org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8
          org.gradle.workers.max=1
          org.gradle.daemon=false
          org.gradle.unsafe.configuration-cache=false
          android.useAndroidX=true
          android.enableJetifier=false
          kotlin.daemon.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m
          PROPS
          echo "wrote android/gradle.properties:"
          cat android/gradle.properties

      - name: flutter pub get
        run: flutter pub get

      # ✅ Build the AAB with reduced memory pressure
      #    (no shrinking, no icon tree-shake; limit ABIs to arm64 for now)
      - name: Build AAB (release)
        run: |
          flutter build appbundle \
            --release \
            --no-shrink \
            --no-tree-shake-icons \
            --target-platform=android-arm64

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
