name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"
      - ".github/workflows/build-debug-apk.yml"

jobs:
  build-debug:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      JAVA_TOOL_OPTIONS: "-Xmx1g -XX:MaxMetaspaceSize=384m"
      _JAVA_OPTIONS: "-Xmx1g"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show Flutter env
        run: |
          flutter --version
          java -version

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: |
          flutter build apk --debug --no-shrink --no-tree-shake-icons

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
